server:
  port: 8082

spring:
  application:
    name: eureka-client

eureka:
  instance:
    instance-id: eureka-client3
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      zone: beijing2
  client:
    service-url:
      beijing2: http://eureka-server-9002.com:9002/eureka/
      beijing1: http://eureka-server-9001.com:9001/eureka/
    region: beijing
    availability-zones:
      beijing: beijing2,beijing1
