server:
  port: 8080

spring:
  application:
    name: eureka-client

eureka:
  instance:
    instance-id: eureka-client1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      zone: beijing1
  client:
    service-url:
      beijing1: http://eureka-server-9001.com:9001/eureka/
      beijing2: http://eureka-server-9002.com:9002/eureka/
    region: henan
    availability-zones:
      beijing: beijing1,beijing2