server:
  port: 9997

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LinkedBear/spring-cloud-source-config-repository.git

eureka:
  instance:
    instance-id: config-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server-9001.com:9001/eureka/