server:
  port: 9003

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server-9003.com
  server:
    registry-sync-retry-wait-ms: 5000
  client:
    service-url:
      defaultZone: http://eureka-server-9001.com:9001/eureka/, http://eureka-server-9002.com:9002/eureka/