server:
  port: 7300

spring:
  application:
    name: hystrix-consumer

eureka:
  instance:
    instance-id: hystrix-consumer
  client:
    service-url:
      defaultZone: http://eureka-server-9001.com:9001/eureka/
#feign:
#  hystrix:
#    enabled: true