server:
  port: 9002

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server-9002.com
  server:
    registry-sync-retry-wait-ms: 5000
    retention-time-in-m-s-in-delta-queue: 30000
  client:
    service-url:
      defaultZone: http://eureka-server-9001.com:9001/eureka/ #, http://eureka-server-9003.com:9003/eureka/